made changes so it could work

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,80 +1,103 @@
-FROM ubuntu:18.04
+FROM ubuntu:20.04
 
-ENV DEBIAN_FRONTEND noninteractive
+ENV DEBIAN_FRONTEND=noninteractive
 
 # Install base dependencies
 
-RUN set -ex; \
-    apt-get update -y; \
-    apt-get install -q -y locales; \
-    rm -rf /var/lib/apt/lists/*; \
-    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-ENV LANG en_US.utf8
+# Install UTF-8 unicode
+RUN echo "**** Install UTF-8 ****" \
+    && apt-get update \
+    && apt-get install -y locales apt-utils debconf-utils
+RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
 
-RUN set -ex; \
-    dpkg --add-architecture i386; \
-    apt-get update -y; \
-    apt-get install -y \
-    vim \
-    apt-transport-https \
+## Upgrade Ubuntu
+RUN echo "**** apt upgrade ****" \
+    && apt-get update; \
+    apt-get upgrade -y
+
+## Install Base LinuxGSM Requirements
+RUN echo "**** Install Base LinuxGSM Requirements ****" \
+    && apt-get update \
+    && apt-get install -y software-properties-common \
+    && add-apt-repository multiverse \
+    && apt-get update \
+    && apt-get install -y \
     bc \
     binutils \
     bsdmainutils \
     bzip2 \
     ca-certificates \
+	cron \
+    cpio \
+    dos2unix\
     curl \
-    default-jre \
-    expect \
+    distro-info \
     file \
     gzip \
-    iproute2 \
+    hostname \
     jq \
     lib32gcc1 \
     lib32stdc++6 \
-    lib32tinfo5 \
-    lib32z1 \
-    libcurl4-gnutls-dev:i386 \
-    libdbus-glib-1-2:i386 \
-    libglu1-mesa:i386 \
-    libldap-2.4-2:i386 \
-    libncurses5:i386 \
-    libnm-glib-dev:i386 \
-    libnm-glib4:i386 \
-    libopenal1:i386 \
-    libpulse0:i386 \
-    libsdl1.2debian \
-    libsdl2-2.0-0:i386 \
-    libssl1.0.0:i386 \
-    libstdc++5:i386 \
-    libstdc++6 \
-    libstdc++6:i386 \
-    libtbb2 \
-    libtcmalloc-minimal4:i386 \
-    libusb-1.0-0:i386 \
-    libxrandr2:i386 \
-    libxtst6:i386 \
-    mailutils \
     netcat \
-    postfix \
-    python \
-    speex:i386 \
+    python3 \
     tar \
-    telnet \
     tmux \
     unzip \
     util-linux \
     wget \
     xz-utils \
-    zlib1g \
-    zlib1g:i386 \
+    # Docker Extras
     cron \
-    gosu; \
-    apt-get clean; \
-    rm -rf /var/lib/apt/lists/*
+    iproute2 \
+    iputils-ping \
+    nano \
+    vim \
+    sudo \
+    tini
+
+# Install SteamCMD
+RUN echo "**** Install SteamCMD ****" \
+    && echo steam steam/question select "I AGREE" | debconf-set-selections \
+    && echo steam steam/license note '' | debconf-set-selections \
+    && dpkg --add-architecture i386 \
+    && apt-get update -y \
+    && apt-get install -y --no-install-recommends \
+    libatomic1 \
+    libpulse0 \
+    libpulse-dev \
+    libc6-dev \
+    libsdl2-2.0-0:i386 \
+    steamcmd \
+    && ln -s /usr/games/steamcmd /usr/bin/steamcmd
+
+# Install NodeJS
+RUN echo "**** Install NodeJS ****" \
+    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
+    && apt-get update && apt-get install -y nodejs
+
+# Install GameDig https://docs.linuxgsm.com/requirements/gamedig
+RUN echo "**** Install GameDig ****" \
+    && npm install -g gamedig
+
+# Install Cleanup
+RUN echo "**** Cleanup ****"  \
+    && apt-get -y autoremove \
+    && apt-get -y clean \
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -rf /tmp/* \
+    && rm -rf /var/tmp/*
+
+##Need use xterm for LinuxGSM##
+
+ENV DEBIAN_FRONTEND=noninteractive
+
+ARG USERNAME=linuxgsm
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
 
 # Install linuxgsm
-
 RUN wget https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh
 
 RUN set -ex; \
@@ -94,34 +117,98 @@ WORKDIR /home/linuxgsm
 ENV TERM=xterm
 ENV PATH=$PATH:/home/linuxgsm
 
-# Install steamcmd
-
-USER root
-
-RUN echo steam steam/question select "I AGREE" | debconf-set-selections; \
-    echo steam steam/license note '' | debconf-set-selections; \
-    dpkg --add-architecture i386; \
-    apt-get update -y; \
-    apt-get install -q -y --no-install-recommends steamcmd; \
-    ln -sf /usr/games/steamcmd /usr/bin/steamcmd; \
-    apt-get autoremove -q -y; \
-    rm -rf /var/lib/apt/lists/*;
 
 # Install vhserver
-
+USER root
 COPY ./vhserverstart.sh .
-RUN chmod +x vhserverstart.sh;
+RUN  chmod +x vhserverstart.sh;
+RUN dos2unix vhserverstart.sh;
+RUN apt update -y ;
+RUN dpkg --add-architecture i386; apt update; apt install distro-info libpulse-dev pigz -y
+RUN apt install uuid-runtime -y 
 
 USER linuxgsm
 
-RUN echo 109 | ./linuxgsm.sh install; \
+RUN echo 127 | ./linuxgsm.sh install; \
     printf "Y\nY\nY\n" | vhserver install; \
     mkdir valheimgameserverbackup;
 
 COPY ./vhserver.cfg ./lgsm/config-lgsm/vhserver/
 
-# Container config
+USER root
+RUN chgrp linuxgsm /home/linuxgsm/lgsm/config-lgsm/vhserver/vhserver.cfg 
+RUN chown linuxgsm /home/linuxgsm/lgsm/config-lgsm/vhserver/vhserver.cfg
+RUN dos2unix /home/linuxgsm/lgsm/config-lgsm/vhserver/vhserver.cfg
 
+# Container config
+USER linuxgsm
 EXPOSE 2456-2458
+
+# # Install linuxgsm
+
+# RUN wget https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh
+
+# RUN set -ex; \
+#     groupadd -g 750 -o linuxgsm; \
+#     adduser --uid 750 --disabled-password --gecos "" --ingroup linuxgsm linuxgsm; \
+#     chown linuxgsm:linuxgsm /linuxgsm.sh; \
+#     chmod +x /linuxgsm.sh; \
+#     cp /linuxgsm.sh /home/linuxgsm/linuxgsm.sh; \
+#     usermod -G tty linuxgsm; \
+#     chown -R linuxgsm:linuxgsm /home/linuxgsm/; \
+#     chmod 755 /home/linuxgsm
+
+# USER linuxgsm
+
+# WORKDIR /home/linuxgsm
+
+# ENV TERM=xterm
+# ENV PATH=$PATH:/home/linuxgsm
+# ENV value=127
+
+# # Install steamcmd
+
+# USER root
+# RUN apt update -y ;
+# RUN dpkg --add-architecture i386; apt update; apt install distro-info libpulse-dev pigz -y
+
+# #install dos2unix 
+# RUN apt-get install dos2unix;
+
+# RUN echo steam steam/question select "I AGREE" | debconf-set-selections; \
+#     echo steam steam/license note '' | debconf-set-selections; \
+#     dpkg --add-architecture i386; \
+#     apt-get update -y; \
+#     apt-get install -q -y --no-install-recommends steamcmd; \
+#     ln -sf /usr/games/steamcmd /usr/bin/steamcmd; \
+#     apt-get autoremove -q -y; \
+#     rm -rf /var/lib/apt/lists/*;
+
+# USER linuxgsm
+# COPY ./vhserverstart.sh .
+
+# USER root
+# #convert DOS to UNIX like
+# RUN chmod +x vhserverstart.sh;
+# RUN dos2unix vhserverstart.sh;
+# RUN dos2unix -r /home/linuxgsm/
+
+# USER linuxgsm
+# RUN chmod +x /home/linuxgsm/linuxgsm.sh;
+# # 127 is valheim server install
+# RUN echo "127" | /home/linuxgsm/linuxgsm.sh install; 
+# RUN yes | vhserver install; 
+# RUN mkdir valheimgameserverbackup;
+
+
+# COPY ./vhserver.cfg ./lgsm/config-lgsm/vhserver/
+# USER root
+# RUN chgrp linuxgsm /home/linuxgsm/lgsm/config-lgsm/vhserver/vhserver.cfg 
+# RUN chown linuxgsm /home/linuxgsm/lgsm/config-lgsm/vhserver/vhserver.cfg
+
+# USER linuxgsm
+# # # Container config
+
+# EXPOSE 2456-2458
 
 ENTRYPOINT ["vhserverstart.sh"]
